export const gulfColData = [
  {
    "Country": "UAE",
    "City": "Dubai",
    "Currency": "AED",
    "Rent 1BR (Monthly)": 8700,
    "Rent 3BR (Monthly)": 16540,
    "Utilities & Internet": 1450,
    "Schooling (Per Child/Mo)": 4500,
    "Groceries (Family 4/Mo)": 4200,
    "Transport (Monthly)": 1200
  },
  {
    "Country": "UAE",
    "City": "Abu Dhabi",
    "Currency": "AED",
    "Rent 1BR (Monthly)": 7800,
    "Rent 3BR (Monthly)": 14200,
    "Utilities & Internet": 1300,
    "Schooling (Per Child/Mo)": 4200,
    "Groceries (Family 4/Mo)": 3900,
    "Transport (Monthly)": 1000
  },
  {
    "Country": "UAE",
    "City": "Sharjah",
    "Currency": "AED",
    "Rent 1BR (Monthly)": 4200,
    "Rent 3BR (Monthly)": 7800,
    "Utilities & Internet": 1100,
    "Schooling (Per Child/Mo)": 2800,
    "Groceries (Family 4/Mo)": 3400,
    "Transport (Monthly)": 800
  },
  {
    "Country": "UAE",
    "City": "Ajman",
    "Currency": "AED",
    "Rent 1BR (Monthly)": 3200,
    "Rent 3BR (Monthly)": 5500,
    "Utilities & Internet": 1000,
    "Schooling (Per Child/Mo)": 2200,
    "Groceries (Family 4/Mo)": 3100,
    "Transport (Monthly)": 700
  },
  {
    "Country": "UAE",
    "City": "Ras Al Khaimah",
    "Currency": "AED",
    "Rent 1BR (Monthly)": 3500,
    "Rent 3BR (Monthly)": 6200,
    "Utilities & Internet": 950,
    "Schooling (Per Child/Mo)": 2500,
    "Groceries (Family 4/Mo)": 3000,
    "Transport (Monthly)": 650
  },
  {
    "Country": "UAE",
    "City": "Fujairah",
    "Currency": "AED",
    "Rent 1BR (Monthly)": 3000,
    "Rent 3BR (Monthly)": 5200,
    "Utilities & Internet": 900,
    "Schooling (Per Child/Mo)": 2000,
    "Groceries (Family 4/Mo)": 2900,
    "Transport (Monthly)": 600
  },
  {
    "Country": "UAE",
    "City": "Al Ain",
    "Currency": "AED",
    "Rent 1BR (Monthly)": 4500,
    "Rent 3BR (Monthly)": 8200,
    "Utilities & Internet": 1050,
    "Schooling (Per Child/Mo)": 3000,
    "Groceries (Family 4/Mo)": 3300,
    "Transport (Monthly)": 750
  },
  {
    "Country": "Saudi Arabia",
    "City": "Riyadh",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 5500,
    "Rent 3BR (Monthly)": 10500,
    "Utilities & Internet": 1200,
    "Schooling (Per Child/Mo)": 3800,
    "Groceries (Family 4/Mo)": 3600,
    "Transport (Monthly)": 900
  },
  {
    "Country": "Saudi Arabia",
    "City": "Jeddah",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 4800,
    "Rent 3BR (Monthly)": 8900,
    "Utilities & Internet": 1100,
    "Schooling (Per Child/Mo)": 3400,
    "Groceries (Family 4/Mo)": 3400,
    "Transport (Monthly)": 850
  },
  {
    "Country": "Saudi Arabia",
    "City": "Dammam",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 3800,
    "Rent 3BR (Monthly)": 7200,
    "Utilities & Internet": 950,
    "Schooling (Per Child/Mo)": 2800,
    "Groceries (Family 4/Mo)": 3100,
    "Transport (Monthly)": 700
  },
  {
    "Country": "Saudi Arabia",
    "City": "Al Khobar",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 4200,
    "Rent 3BR (Monthly)": 7900,
    "Utilities & Internet": 1000,
    "Schooling (Per Child/Mo)": 3100,
    "Groceries (Family 4/Mo)": 3200,
    "Transport (Monthly)": 750
  },
  {
    "Country": "Saudi Arabia",
    "City": "Mecca",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 4500,
    "Rent 3BR (Monthly)": 8500,
    "Utilities & Internet": 1050,
    "Schooling (Per Child/Mo)": 2500,
    "Groceries (Family 4/Mo)": 3300,
    "Transport (Monthly)": 800
  },
  {
    "Country": "Saudi Arabia",
    "City": "Medina",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 3500,
    "Rent 3BR (Monthly)": 6500,
    "Utilities & Internet": 900,
    "Schooling (Per Child/Mo)": 2200,
    "Groceries (Family 4/Mo)": 3000,
    "Transport (Monthly)": 650
  },
  {
    "Country": "Saudi Arabia",
    "City": "Jubail",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 3200,
    "Rent 3BR (Monthly)": 5800,
    "Utilities & Internet": 850,
    "Schooling (Per Child/Mo)": 2500,
    "Groceries (Family 4/Mo)": 2900,
    "Transport (Monthly)": 700
  },
  {
    "Country": "Saudi Arabia",
    "City": "Yanbu",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 2800,
    "Rent 3BR (Monthly)": 5200,
    "Utilities & Internet": 800,
    "Schooling (Per Child/Mo)": 2000,
    "Groceries (Family 4/Mo)": 2700,
    "Transport (Monthly)": 600
  },
  {
    "Country": "Saudi Arabia",
    "City": "Taif",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 2500,
    "Rent 3BR (Monthly)": 4800,
    "Utilities & Internet": 750,
    "Schooling (Per Child/Mo)": 1800,
    "Groceries (Family 4/Mo)": 2600,
    "Transport (Monthly)": 550
  },
  {
    "Country": "Saudi Arabia",
    "City": "Tabuk",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 2200,
    "Rent 3BR (Monthly)": 4200,
    "Utilities & Internet": 700,
    "Schooling (Per Child/Mo)": 1600,
    "Groceries (Family 4/Mo)": 2500,
    "Transport (Monthly)": 500
  },
  {
    "Country": "Saudi Arabia",
    "City": "Abha",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 2400,
    "Rent 3BR (Monthly)": 4500,
    "Utilities & Internet": 750,
    "Schooling (Per Child/Mo)": 1700,
    "Groceries (Family 4/Mo)": 2600,
    "Transport (Monthly)": 500
  },
  {
    "Country": "Saudi Arabia",
    "City": "Buraidah",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 2000,
    "Rent 3BR (Monthly)": 3800,
    "Utilities & Internet": 650,
    "Schooling (Per Child/Mo)": 1500,
    "Groceries (Family 4/Mo)": 2400,
    "Transport (Monthly)": 450
  },
  {
    "Country": "Saudi Arabia",
    "City": "Jazan",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 2100,
    "Rent 3BR (Monthly)": 4000,
    "Utilities & Internet": 680,
    "Schooling (Per Child/Mo)": 1500,
    "Groceries (Family 4/Mo)": 2500,
    "Transport (Monthly)": 480
  },
  {
    "Country": "Saudi Arabia",
    "City": "Najran",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 1900,
    "Rent 3BR (Monthly)": 3600,
    "Utilities & Internet": 650,
    "Schooling (Per Child/Mo)": 1400,
    "Groceries (Family 4/Mo)": 2300,
    "Transport (Monthly)": 450
  },
  {
    "Country": "Saudi Arabia",
    "City": "Hail",
    "Currency": "SAR",
    "Rent 1BR (Monthly)": 2000,
    "Rent 3BR (Monthly)": 3700,
    "Utilities & Internet": 650,
    "Schooling (Per Child/Mo)": 1500,
    "Groceries (Family 4/Mo)": 2400,
    "Transport (Monthly)": 450
  },
  {
    "Country": "Qatar",
    "City": "Doha",
    "Currency": "QAR",
    "Rent 1BR (Monthly)": 7500,
    "Rent 3BR (Monthly)": 14000,
    "Utilities & Internet": 1200,
    "Schooling (Per Child/Mo)": 4500,
    "Groceries (Family 4/Mo)": 4200,
    "Transport (Monthly)": 1000
  },
  {
    "Country": "Qatar",
    "City": "Al Wakrah",
    "Currency": "QAR",
    "Rent 1BR (Monthly)": 5200,
    "Rent 3BR (Monthly)": 9500,
    "Utilities & Internet": 1050,
    "Schooling (Per Child/Mo)": 3200,
    "Groceries (Family 4/Mo)": 3600,
    "Transport (Monthly)": 850
  },
  {
    "Country": "Qatar",
    "City": "Al Rayyan",
    "Currency": "QAR",
    "Rent 1BR (Monthly)": 6000,
    "Rent 3BR (Monthly)": 11000,
    "Utilities & Internet": 1100,
    "Schooling (Per Child/Mo)": 3500,
    "Groceries (Family 4/Mo)": 3800,
    "Transport (Monthly)": 900
  },
  {
    "Country": "Qatar",
    "City": "Al Khor",
    "Currency": "QAR",
    "Rent 1BR (Monthly)": 4800,
    "Rent 3BR (Monthly)": 8800,
    "Utilities & Internet": 1000,
    "Schooling (Per Child/Mo)": 2800,
    "Groceries (Family 4/Mo)": 3400,
    "Transport (Monthly)": 800
  },
  {
    "Country": "Qatar",
    "City": "Mesaieed",
    "Currency": "QAR",
    "Rent 1BR (Monthly)": 4200,
    "Rent 3BR (Monthly)": 7500,
    "Utilities & Internet": 950,
    "Schooling (Per Child/Mo)": 2500,
    "Groceries (Family 4/Mo)": 3200,
    "Transport (Monthly)": 750
  },
  {
    "Country": "Kuwait",
    "City": "Kuwait City",
    "Currency": "KWD",
    "Rent 1BR (Monthly)": 450,
    "Rent 3BR (Monthly)": 850,
    "Utilities & Internet": 70,
    "Schooling (Per Child/Mo)": 350,
    "Groceries (Family 4/Mo)": 320,
    "Transport (Monthly)": 80
  },
  {
    "Country": "Kuwait",
    "City": "Salmiya",
    "Currency": "KWD",
    "Rent 1BR (Monthly)": 380,
    "Rent 3BR (Monthly)": 720,
    "Utilities & Internet": 65,
    "Schooling (Per Child/Mo)": 300,
    "Groceries (Family 4/Mo)": 290,
    "Transport (Monthly)": 75
  },
  {
    "Country": "Kuwait",
    "City": "Hawalli",
    "Currency": "KWD",
    "Rent 1BR (Monthly)": 320,
    "Rent 3BR (Monthly)": 600,
    "Utilities & Internet": 60,
    "Schooling (Per Child/Mo)": 280,
    "Groceries (Family 4/Mo)": 270,
    "Transport (Monthly)": 70
  },
  {
    "Country": "Kuwait",
    "City": "Al Ahmadi",
    "Currency": "KWD",
    "Rent 1BR (Monthly)": 280,
    "Rent 3BR (Monthly)": 550,
    "Utilities & Internet": 55,
    "Schooling (Per Child/Mo)": 250,
    "Groceries (Family 4/Mo)": 260,
    "Transport (Monthly)": 65
  },
  {
    "Country": "Kuwait",
    "City": "Jahra",
    "Currency": "KWD",
    "Rent 1BR (Monthly)": 250,
    "Rent 3BR (Monthly)": 480,
    "Utilities & Internet": 50,
    "Schooling (Per Child/Mo)": 220,
    "Groceries (Family 4/Mo)": 250,
    "Transport (Monthly)": 60
  },
  {
    "Country": "Bahrain",
    "City": "Manama",
    "Currency": "BHD",
    "Rent 1BR (Monthly)": 380,
    "Rent 3BR (Monthly)": 750,
    "Utilities & Internet": 95,
    "Schooling (Per Child/Mo)": 380,
    "Groceries (Family 4/Mo)": 350,
    "Transport (Monthly)": 85
  },
  {
    "Country": "Bahrain",
    "City": "Riffa",
    "Currency": "BHD",
    "Rent 1BR (Monthly)": 320,
    "Rent 3BR (Monthly)": 620,
    "Utilities & Internet": 85,
    "Schooling (Per Child/Mo)": 320,
    "Groceries (Family 4/Mo)": 310,
    "Transport (Monthly)": 75
  },
  {
    "Country": "Bahrain",
    "City": "Muharraq",
    "Currency": "BHD",
    "Rent 1BR (Monthly)": 280,
    "Rent 3BR (Monthly)": 580,
    "Utilities & Internet": 80,
    "Schooling (Per Child/Mo)": 300,
    "Groceries (Family 4/Mo)": 300,
    "Transport (Monthly)": 70
  },
  {
    "Country": "Bahrain",
    "City": "Hamad Town",
    "Currency": "BHD",
    "Rent 1BR (Monthly)": 220,
    "Rent 3BR (Monthly)": 450,
    "Utilities & Internet": 70,
    "Schooling (Per Child/Mo)": 240,
    "Groceries (Family 4/Mo)": 270,
    "Transport (Monthly)": 60
  },
  {
    "Country": "Bahrain",
    "City": "Isa Town",
    "Currency": "BHD",
    "Rent 1BR (Monthly)": 240,
    "Rent 3BR (Monthly)": 480,
    "Utilities & Internet": 75,
    "Schooling (Per Child/Mo)": 250,
    "Groceries (Family 4/Mo)": 280,
    "Transport (Monthly)": 65
  },
  {
    "Country": "Bahrain",
    "City": "Sitra",
    "Currency": "BHD",
    "Rent 1BR (Monthly)": 200,
    "Rent 3BR (Monthly)": 420,
    "Utilities & Internet": 65,
    "Schooling (Per Child/Mo)": 220,
    "Groceries (Family 4/Mo)": 260,
    "Transport (Monthly)": 60
  },
  {
    "Country": "Bahrain",
    "City": "Budaiya",
    "Currency": "BHD",
    "Rent 1BR (Monthly)": 300,
    "Rent 3BR (Monthly)": 600,
    "Utilities & Internet": 85,
    "Schooling (Per Child/Mo)": 330,
    "Groceries (Family 4/Mo)": 310,
    "Transport (Monthly)": 75
  },
  {
    "Country": "Bahrain",
    "City": "Juffair",
    "Currency": "BHD",
    "Rent 1BR (Monthly)": 450,
    "Rent 3BR (Monthly)": 850,
    "Utilities & Internet": 100,
    "Schooling (Per Child/Mo)": 400,
    "Groceries (Family 4/Mo)": 360,
    "Transport (Monthly)": 90
  },
  {
    "Country": "Oman",
    "City": "Muscat",
    "Currency": "OMR",
    "Rent 1BR (Monthly)": 420,
    "Rent 3BR (Monthly)": 820,
    "Utilities & Internet": 110,
    "Schooling (Per Child/Mo)": 320,
    "Groceries (Family 4/Mo)": 300,
    "Transport (Monthly)": 85
  },
  {
    "Country": "Oman",
    "City": "Salalah",
    "Currency": "OMR",
    "Rent 1BR (Monthly)": 280,
    "Rent 3BR (Monthly)": 550,
    "Utilities & Internet": 90,
    "Schooling (Per Child/Mo)": 240,
    "Groceries (Family 4/Mo)": 260,
    "Transport (Monthly)": 70
  },
  {
    "Country": "Oman",
    "City": "Sohar",
    "Currency": "OMR",
    "Rent 1BR (Monthly)": 320,
    "Rent 3BR (Monthly)": 600,
    "Utilities & Internet": 95,
    "Schooling (Per Child/Mo)": 260,
    "Groceries (Family 4/Mo)": 270,
    "Transport (Monthly)": 75
  },
  {
    "Country": "Oman",
    "City": "Nizwa",
    "Currency": "OMR",
    "Rent 1BR (Monthly)": 250,
    "Rent 3BR (Monthly)": 480,
    "Utilities & Internet": 85,
    "Schooling (Per Child/Mo)": 220,
    "Groceries (Family 4/Mo)": 250,
    "Transport (Monthly)": 65
  },
  {
    "Country": "Oman",
    "City": "Sur",
    "Currency": "OMR",
    "Rent 1BR (Monthly)": 240,
    "Rent 3BR (Monthly)": 450,
    "Utilities & Internet": 80,
    "Schooling (Per Child/Mo)": 210,
    "Groceries (Family 4/Mo)": 250,
    "Transport (Monthly)": 60
  },
  {
    "Country": "Oman",
    "City": "Ibri",
    "Currency": "OMR",
    "Rent 1BR (Monthly)": 210,
    "Rent 3BR (Monthly)": 400,
    "Utilities & Internet": 75,
    "Schooling (Per Child/Mo)": 190,
    "Groceries (Family 4/Mo)": 240,
    "Transport (Monthly)": 55
  },
  {
    "Country": "Oman",
    "City": "Rustaq",
    "Currency": "OMR",
    "Rent 1BR (Monthly)": 220,
    "Rent 3BR (Monthly)": 410,
    "Utilities & Internet": 75,
    "Schooling (Per Child/Mo)": 200,
    "Groceries (Family 4/Mo)": 240,
    "Transport (Monthly)": 60
  },
  {
    "Country": "Oman",
    "City": "Khasab",
    "Currency": "OMR",
    "Rent 1BR (Monthly)": 350,
    "Rent 3BR (Monthly)": 650,
    "Utilities & Internet": 100,
    "Schooling (Per Child/Mo)": 250,
    "Groceries (Family 4/Mo)": 280,
    "Transport (Monthly)": 70
  },
  {
    "Country": "Oman",
    "City": "Duqm",
    "Currency": "OMR",
    "Rent 1BR (Monthly)": 400,
    "Rent 3BR (Monthly)": 750,
    "Utilities & Internet": 105,
    "Schooling (Per Child/Mo)": 280,
    "Groceries (Family 4/Mo)": 290,
    "Transport (Monthly)": 80
  },
  {
    "Country": "Oman",
    "City": "Buraimi",
    "Currency": "OMR",
    "Rent 1BR (Monthly)": 230,
    "Rent 3BR (Monthly)": 430,
    "Utilities & Internet": 80,
    "Schooling (Per Child/Mo)": 200,
    "Groceries (Family 4/Mo)": 245,
    "Transport (Monthly)": 60
  }
];